#!/bin/sh
d=${PWD}
cmake 	-DCMAKE_BUILD_TYPE=RELEASE \
	-DCMAKE_INSTALL_PREFIX="${d}" \
	-DBUILD_TESTS=OFF \
	-DBUILD_SHARED_LIBS=OFF \
	-DBUILD_EXAMPLES=OFF \
	-DBUILD_WITH_DEBUG_INFO=OFF \
	-DBUILD_NEW_PYTHON_SUPPORT=OFF \
	-DCMAKE_OSX_ARCHITECTURES="i386" \
	-DWITH_CUDA=OFF \
	-DWITH_EIGEN=OFF \
	-DWITH_FFMPEG=OFF \
	-DWITH_JASPER=OFF \
	-DWITH_JPEG=OFF \
	-DWITH_OPENEXR=OFF \
	-DWITH_PNG=OFF \
	-DWITH_PVAPI=OFF \
	-DWITH_TIFF=OFF \
	../
