#ifndef ROXLUINCLUDESH
#define ROXLUINCLUDESH

#include "roxlu/ArcBall.h"
#include "roxlu/Camera.h"
#include "roxlu/Color.h"
#include "roxlu/Constants.h"
#include "roxlu/Dictionary.h"
#include "roxlu/DictionaryMap.h"
#include "roxlu/EasyCam.h"
#include "roxlu/Endianness.h"
#include "roxlu/Error.h"
#include "roxlu/FBO.h"
#include "roxlu/IcoSphere.h"
#include "roxlu/INI.h"
#include "roxlu/IOBuffer.h"
#include "roxlu/Mat3.h"
#include "roxlu/Mat4.h"
#include "roxlu/OpenGL.h"
#include "roxlu/OBJ.h"
#include "roxlu/PBO.h"
#include "roxlu/Ply.h"
#include "roxlu/Quad.h"
#include "roxlu/Quat.h"
#include "roxlu/Renderer.h"
#include "roxlu/Ray.h"
#include "roxlu/SceneItem.h"
#include "roxlu/Scene.h"
#include "roxlu/Shader.h"
#include "roxlu/Sphere.h"
#include "roxlu/Triangle.h"
#include "roxlu/Utils.h"
#include "roxlu/VAO.h"
#include "roxlu/VBO.h"
#include "roxlu/Vec2.h"
#include "roxlu/Vec3.h"
#include "roxlu/Vec4.h"
#include "roxlu/VertexData.h"
#include "roxlu/VertexTypes.h"

#include "roxlu/HalfEdge/HE_Edge.h"
#include "roxlu/HalfEdge/HE_Face.h"
#include "roxlu/HalfEdge/HE_HalfEdge.h"
#include "roxlu/HalfEdge/HE_Mesh.h"
#include "roxlu/HalfEdge/HE_Selection.h"
#include "roxlu/HalfEdge/HE_Structure.h"
#include "roxlu/HalfEdge/HE_Vertex.h"
#include "roxlu/HalfEdge/HEC_Creator.h"
#include "roxlu/HalfEdge/HEC_FromFaceList.h"
#include "roxlu/HalfEdge/HEC_FromTriangles.h"
#include "roxlu/HalfEdge/HEC_Plane.h"
#include "roxlu/HalfEdge/HEM_Bend.h"
#include "roxlu/HalfEdge/HEM_Modifier.h"
#include "roxlu/HalfEdge/HEM_Noise.h"
#include "roxlu/HalfEdge/HES_CatmullClark.h"
#include "roxlu/HalfEdge/HES_Subdividor.h"

#include "roxlu/experimental/File.h"
#include "roxlu/experimental/StringUtil.h"
#include "roxlu/experimental/UVSphere.h"
#include "roxlu/experimental/SimpleServer.h"
#include "roxlu/experimental/SimpleClient.h"

#include "external/jpeg/JPEGImage.h"
#include "external/webp/WebPImage.h"

using namespace roxlu;


#endif